name: LuckyBlock
version: "0.0.2"
author: Palente
main: Palente\LuckyBlock\Main
description: "a Lucky Block plugin by Palente"
website: "https://github.com/Palente"
softdepend: ["EconomyAPI"]
api: [3.2.3]