name: LuckyBlock
main: palente\luckyblock\Main
version: 1.2.0
author:
  - Palente
  - Bluzzi
api: 4.0.0
softdepend: ["EconomyAPI", "PiggyCustomEnchants", "BedrockEconomy"]

description: "A Lucky Block Plugin by Palente"
website: "https://github.com/Palente/LuckyBlock"